============================= test session starts ==============================
platform linux -- Python 3.11.3, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/runner/work/Assessment-Fundamentals-Week-2/Assessment-Fundamentals-Week-2
plugins: md-0.2.0, emoji-0.2.0
collected 9 items / 2 errors

==================================== ERRORS ====================================
__________________ ERROR collecting Level-2/test_two_task.py ___________________
ImportError while importing test module '/home/runner/work/Assessment-Fundamentals-Week-2/Assessment-Fundamentals-Week-2/Level-2/test_two_task.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
Level-2/test_two_task.py:1: in <module>
    from task_two import MultipleChoiceAssessment, TechnicalAssessment, PresentationAssessment, Assessment, Trainee
E   ImportError: cannot import name 'MultipleChoiceAssessment' from 'task_two' (/home/runner/work/Assessment-Fundamentals-Week-2/Assessment-Fundamentals-Week-2/Level-2/task_two.py)
_________________ ERROR collecting Level-3/test_three_task.py __________________
ImportError while importing test module '/home/runner/work/Assessment-Fundamentals-Week-2/Assessment-Fundamentals-Week-2/Level-3/test_three_task.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
Level-3/test_three_task.py:1: in <module>
    from task_three import Marking, Quiz, Question, MultipleChoiceAssessment, Assessment, TechnicalAssessment
E   ImportError: cannot import name 'MultipleChoiceAssessment' from 'task_three' (/home/runner/work/Assessment-Fundamentals-Week-2/Assessment-Fundamentals-Week-2/Level-3/task_three.py)
=========================== short test summary info ============================
ERROR Level-2/test_two_task.py
ERROR Level-3/test_three_task.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 2 errors in 0.09s ===============================
